services:
  server:
    container_name: dev-server
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile.dev
    restart: always
    image: dev-server
    ports:
      - 3001:3001
    volumes:
      - ../../src:/usr/src/app/src
